[package]
name = "bevy_builder"
version = "0.1.0"
edition = "2021"
exclude = ["/examples"]

[dependencies]
bevy = { version = "=0.13.0", default-features = false, features = ["bevy_ui", "bevy_asset"] }
bevy-trait-query = "0.5.1"
common = { git = "https://github.com/empathic-ai/common.git" }
serde = { version = "1.0.149", features = ["derive"] }
lazy_static = "1.4.0"